# permissions for end users to edit clowdjobinvocations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    olm.opgroup.permissions/aggregate-to-edit: clowder
  name: clowdjobinvocation-editor-role
rules:
- apiGroups:
  - cloud.redhat.com
  resources:
  - clowdjobinvocations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.redhat.com
  resources:
  - clowdjobinvocations/status
  verbs:
  - get
